name: Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run test

    - name: Upload Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress/screenshots

    - name: Upload Artifacts on Success
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-reports
        path: cypress/reports/html
